apiVersion: v1
kind: Service
metadata:
  name: signup-service
  labels:
    app: signup
spec:
  ports:
  - port: 8081
    targetPort: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: signup
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: signup-v1
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: signup
        version: v1
    spec:
      containers:
      - name: signup
        image: loopcs/signup-microservice:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080